- name: Check for keystone running under apache
  tags: common
  shell: httpd -t -D DUMP_VHOSTS | grep -q keystone_wsgi
  ignore_errors: true
  register: httpd_enabled
- name: Check if httpd is running
  tags: common
  command: systemctl is-active --quiet httpd
  ignore_errors: true
  register: httpd_running
- name: 'PreUpgrade step0,validation: Check if keystone_wsgi is running under httpd'
  shell: systemctl status 'httpd' | grep -q keystone
  tags: validation
  when:
  - step|int == 0
  - httpd_enabled.rc == 0
  - httpd_running.rc == 0
- name: Stop and disable keystone service (running under httpd)
  when:
  - step|int == 2
  - httpd_enabled.rc == 0
  - httpd_running.rc == 0
  service: name=httpd state=stopped enabled=no
- name: remove old keystone cron jobs
  when: step|int == 2
  file:
    path: /var/spool/cron/keystone
    state: absent
